const CLAVE="sexomania2024";let editId=null,cache=[];
window.check=function(){let p=document.getElementById("pass").value;if(p===CLAVE){sessionStorage.setItem("sexo_admin","ok");document.getElementById("login").style.display="none";document.getElementById("panel").style.display="block";iniciar();}else{document.getElementById("error").style.display="block";document.getElementById("pass").value="";setTimeout(()=>document.getElementById("error").style.display="none",2000);}}
window.logout=()=>{sessionStorage.removeItem("sexo_admin");location.reload()};
if(sessionStorage.getItem("sexo_admin")==="ok"){document.getElementById("login").style.display="none";document.getElementById("panel").style.display="block";setTimeout(iniciar,400);}
document.getElementById("pass").addEventListener("keypress",e=>{if(e.key==="Enter")check()});
function cargarGaleria(i){let f=i.files[0];if(!f)return;let r=new FileReader();r.onload=e=>{document.getElementById("foto").value=e.target.result;preview(e.target.result)};r.readAsDataURL(f);}
window.preview=u=>{let img=document.getElementById("prev");if(u.length>10){img.src=u;img.style.display="block";img.onerror=()=>img.style.display="none";}};
function iniciar(){onSnap(col(db,"chats"),snap=>{cache=[];snap.forEach(d=>cache.push({id:d.id,...d.data()}));listar();estadisticas();});}
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const CATEGORIAS=[{id:"CANALES ADULTOS",label:"🔞 𝐂𝐚𝐧𝐚𝐥𝐞𝐬 𝐃𝐞 𝐀𝐩𝐨𝐫𝐭𝐞𝐬 𝐗𝐗𝐗 🔞"},{id:"GRUPOS ADULTOS",label:"🔞 𝐆𝐫𝐮𝐩𝐨𝐬 𝐃𝐞 𝐀𝐩𝐨𝐫𝐭𝐞𝐬 𝐗𝐗𝐗 🔞"},{id:"VENTAS +18",label:"VENTAS +18"},{id:"PUBLICITARIOS",label:"📢 𝐂𝐚𝐧𝐚𝐥𝐞𝐬 & 𝐆𝐫𝐮𝐩𝐨𝐬 𝐏𝐮𝐛𝐥𝐢𝐜𝐢𝐭𝐚𝐫𝐢𝐨𝐬 📢"},{id:"ENTRETENIMIENTO",label:"🍿 (𝐂 & 𝐆) 𝐃𝐞 𝐄𝐧𝐭𝐫𝐞𝐭𝐞𝐧𝐢𝐦𝐢𝐞𝐧𝐭𝐨🍿"},{id:"ARTE",label:"🎨 𝐂𝐚𝐧𝐚𝐥𝐞𝐬 & 𝐆𝐫𝐮𝐩𝐨𝐬 𝐃𝐞 𝐀𝐫𝐭𝐞𝐬 🎨"},{id:"VENTA ARTICULOS",label:"VENTA ARTICULOS"},{id:"BOTS",label:"🤖 𝐋𝐨𝐬 𝐌𝐞𝐣𝐨𝐫𝐞𝐬 𝐁𝐎𝐓𝐒 🤖"}];
function itemHTML(c){return `<div class="item"><img src="${esc(c.foto||"")}" style="width:40px;height:40px;border-radius:50%;object-fit:cover;border:1px solid red"><div style="flex:1;margin-left:10px;text-align:left"><b style="font-size:12px;color:#ff6a6a">${esc(c.nombre)}</b><br><span style="font-size:10px;color:silver">👁️ ${c.clicks||0}${c.destacado?" • 📌":""}${c.nuevo?" • 🆕":""}${c.activo===false?" • 🔴 OCULTO":""}</span></div><div style="display:flex;gap:5px"><button class="btn-del" style="background:#222" onclick="editar('${c.id}')">✏️</button><button class="btn-del" style="background:#111" onclick="alternarEstado('${c.id}')">${c.activo===false?"🟢":"🔴"}</button><button class="btn-del" style="background:#552b00" onclick="destacar('${c.id}')">📌</button><button class="btn-del" style="background:red;color:#fff" onclick="borrar('${c.id}')">🗑️</button></div></div>`;}
window.categoriasAbiertas={};
window.toggleCategoria=id=>{
  if(id==="cat-otras"){
    window.categoriasAbiertas.__OTRAS__=!window.categoriasAbiertas.__OTRAS__;
  }else{
    const cat=CATEGORIAS.find(c=>"cat-"+c.id.replace(/[^a-zA-Z0-9]+/g,"-")===id);
    if(cat) window.categoriasAbiertas[cat.id]=!window.categoriasAbiertas[cat.id];
  }
  listar();
};
function listar(){let q=(document.getElementById("filtroAdmin")?.value||"").toLowerCase().trim();let arr=cache.filter(c=>String(c.nombre||"").toLowerCase().includes(q)||String(c.seccion||"").toLowerCase().includes(q));document.getElementById("count").innerText=cache.length;if(!arr.length){document.getElementById("lista").innerHTML='<p style="color:#555;font-size:11px">No hay coincidencias</p>';return;}let html="";CATEGORIAS.forEach(cat=>{let items=arr.filter(c=>c.seccion===cat.id||(cat.id==="VENTAS +18"&&c.seccion==="VENTAS")||(cat.id==="VENTA ARTICULOS"&&c.seccion==="Venta de Articulos"));if(!items.length)return;html+='<section class="cat-group"><button type="button" class="cat-title" onclick="toggleCategoria(\'cat-'+cat.id.replace(/[^a-zA-Z0-9]+/g,\'-\')+\')"><span>📁 '+cat.label+'</span><span class="cat-count">'+items.length+' '+(window.categoriasAbiertas?.[cat.id]?"▲":"▼")+'</span></button><div id="cat-'+cat.id.replace(/[^a-zA-Z0-9]+/g,\'-\')+'" style="display:'+(window.categoriasAbiertas?.[cat.id]?"block":"none")+'">'+items.map(itemHTML).join("")+'</div></section>';});let otros=arr.filter(c=>!CATEGORIAS.some(cat=>cat.id===c.seccion));if(otros.length)html+='<section class="cat-group"><button type="button" class="cat-title" onclick="toggleCategoria(\'cat-otras\')"><span>📂 OTRAS / SIN CATEGORÍA</span><span class="cat-count">'+otros.length+' '+(window.categoriasAbiertas?.__OTRAS__?"▲":"▼")+'</span></button><div id="cat-otras" style="display:'+(window.categoriasAbiertas?.__OTRAS__?"block":"none")+'">'+otros.map(itemHTML).join("")+'</div></section>';document.getElementById("lista").innerHTML=html||'<p style="color:#555;font-size:11px">No hay coincidencias</p>';}
function estadisticas(){document.getElementById("totalChats").innerText=cache.length;document.getElementById("totalViews").innerText=cache.reduce((n,c)=>n+Number(c.clicks||0),0);document.getElementById("activeChats").innerText=cache.filter(c=>c.activo!==false).length;document.getElementById("featuredChats").innerText=cache.filter(c=>c.destacado===true).length;}
window.guardar=async()=>{let datos={seccion:document.getElementById("seccion").value,foto:document.getElementById("foto").value.trim(),nombre:document.getElementById("nombre").value.trim(),desc:document.getElementById("desc").value.trim(),link:document.getElementById("link").value.trim(),etiqueta:document.getElementById("etiqueta").value,tags:document.getElementById("tags").value.split(",").map(x=>x.trim()).filter(Boolean),reporte:document.getElementById("reporte").value.trim(),destacado:document.getElementById("destacado").checked,activo:document.getElementById("activo").checked,nuevo:document.getElementById("nuevo").checked,fecha:stamp()};if(!datos.foto||!datos.nombre||!datos.link){alert("Falta foto, nombre y link");return;}try{if(editId)await upd(docu(db,"chats",editId),datos);else{datos.clicks=0;await add(col(db,"chats"),datos);}limpiar();}catch(e){alert("Error: "+e.message);}};
window.editar=id=>{let c=cache.find(x=>x.id===id);if(!c)return;editId=id;document.getElementById("seccion").value=c.seccion;document.getElementById("foto").value=c.foto||"";preview(c.foto||"");document.getElementById("nombre").value=c.nombre||"";document.getElementById("desc").value=c.desc||"";document.getElementById("link").value=c.link||"";document.getElementById("etiqueta").value=c.etiqueta||"";document.getElementById("tags").value=Array.isArray(c.tags)?c.tags.join(", "):"";document.getElementById("reporte").value=c.reporte||"";document.getElementById("destacado").checked=c.destacado===true;document.getElementById("activo").checked=c.activo!==false;document.getElementById("nuevo").checked=c.nuevo===true;document.getElementById("btnG").innerText="💾 GUARDAR CAMBIOS";document.getElementById("btnC").style.display="block";window.scrollTo({top:0,behavior:"smooth"});};
window.alternarEstado=async id=>{let c=cache.find(x=>x.id===id);if(c)await upd(docu(db,"chats",id),{activo:c.activo===false});};
window.destacar=async id=>{let c=cache.find(x=>x.id===id);if(c)await upd(docu(db,"chats",id),{destacado:c.destacado!==true});};
window.borrar=async id=>{if(!confirm("¿Borrar este chat?"))return;await del(docu(db,"chats",id));};
window.cancelar=()=>limpiar();
function limpiar(){editId=null;["foto","nombre","desc","link","tags","reporte"].forEach(id=>document.getElementById(id).value="");document.getElementById("etiqueta").value="";document.getElementById("destacado").checked=false;document.getElementById("activo").checked=true;document.getElementById("nuevo").checked=false;document.getElementById("prev").style.display="none";document.getElementById("btnG").innerText="🔥 PUBLICAR 🔥";document.getElementById("btnC").style.display="none";}
